default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cei_api_development

test:
  <<: *default
  database: cei_api_test

production:
  primary:
    <<: *default
    database: cei_api_production
  cache:
    <<: *default
    database: cei_api_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: cei_api_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: cei_api_production_cable
    migrations_paths: db/cable_migrate